name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dependencies:
    path: ../dependencies
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  mocktail: ^0.3.0

flutter: