name: pokemon_detail
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  ui_core:
    path: ../../features/ui_core
  dependencies:
    path: ../../dependencies
  domain:
    path: ../../domain
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0

flutter:

scripts: ../../../derry.yaml