name: dependencies
description: A flutter module for dependecy management
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_core: ^1.17.0
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: