name: dependencies
description: A flutter module for dependecy management
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: 1.15.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter: