name: ui_core
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  adaptive_breakpoints: ^0.1.4
  avatar_glow: ^2.0.2
  cached_network_image: ^3.2.1
  dependencies:
    path: ../../dependencies
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  lottie: ^1.3.0
  provider: ^6.0.3
  shimmer: ^2.0.0
  fluttertoast: ^8.0.9

dev_dependencies:
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/gif/
  fonts:
    - family: Pokemon
      fonts:
        - asset: assets/fonts/Pokemon-Solid.ttf

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true

scripts: ../../../derry.yaml