name: build and upload android artifacts

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
      target:
        type: string
        required: true
    secrets:
      SIGNING_KEYSTORE:
        required: true
      SIGNING_KEY_ALIAS:
        required: true
      SIGNING_KEY_PASSWORD:
        required: true
      SIGNING_STORE_PASSWORD:
        required: true

jobs:
  create_release_artifact:
    name: create and upload apk and aab to github
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "12.x"
      FLUTTER_VERSION: "2.10.3"
      SIGNING_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java environment
        uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      - name: Get flutter dependencies
        run: flutter pub get
      - name: Generate icons
        run: flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons/${{ inputs.flavor }}.yaml
      - name: Build apk file
        run: flutter build apk --flavor ${{ inputs.flavor }} -t ${{ inputs.target }}
        timeout-minutes: 20
      - name: Build aab file
        run: flutter build appbundle --flavor ${{ inputs.flavor }} -t ${{ inputs.target }}
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ inputs.flavor }}-release.apk
          path: build/app/outputs/flutter-apk/app-${{ inputs.flavor }}-release.apk
          retention-days: 7
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ inputs.flavor }}-release.aab
          path: build/app/outputs/bundle/${{ inputs.flavor }}Release/app-${{ inputs.flavor }}-release.aab
          retention-days: 7