name: build web

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
      target:
        type: string
        required: true

jobs:
  flutter_test:
    name: apk and aab
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "2.10.3"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      - name: Get flutter dependencies
        run: flutter pub get
      - name: Build web
        run: flutter build web --flavor ${{ inputs.flavor }} -t ${{ inputs.target }}
        timeout-minutes: 60