name: Upload artifacts to Github

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
    secrets:
      DISTRIBUTION_GITHUB_TOKEN:
        required: true

jobs:
  upload_apk_artifact:
    name: Upload apk and aab to github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Upload apk to Github
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-${{ inputs.flavor }}-release.apk
          tag: v1.0.${{ $GITHUB_REF_NAME }}
          token: ${{ secrets.DISTRIBUTION_GITHUB_TOKEN }}

  upload_aab_artifact:
    name: Upload apk and aab to github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Upload aab to Github
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/bundle/${{ inputs.flavor }}Release/app-${{ inputs.flavor }}-release.aab
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.DISTRIBUTION_GITHUB_TOKEN }}

  upload_ios_artifact:
    name: Upload ipa to github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Upload ipa to Github
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/ios/ipa/app-${{ inputs.flavor }}-release.ipa
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.DISTRIBUTION_GITHUB_TOKEN }}
