name: Upload artifacts to Firebase Distribution

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
    secrets:
      FIREBASE_APP_ID:
        required: true
      FIREBASE_TOKEN:
        required: true

jobs:
  create_android_artifact:
    name: create and upload apk and aab to github
    runs-on: ubuntu-latest
    env:
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download APK Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-${{ inputs.flavor }}-release.apk
      - name: Upload APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{ env.FIREBASE_APP_ID }}
          token: ${{ env.FIREBASE_TOKEN }}
          groups: Testers
          file: app-${{ inputs.flavor }}-release.apk
