name: tests

on:
  push:
    tags:
      - '*-prod'

jobs:
  flutter_test:
    uses: ./.github/workflows/_build_test.yml

  build_android_kanto:
    uses: ./.github/workflows/_build_android.yml
    needs: flutter_test
    with:
      flavor: kanto
      target: lib/main_kanto.dart
    secrets:
      SIGNING_KEYSTORE: ${{ secrets.KANTO_KEYSTORE }}
      SIGNING_KEY_ALIAS: ${{ secrets.KANTO_SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}


  build_android_jhoto:
    uses: ./.github/workflows/_build_android.yml
    needs: flutter_test
    with:
      flavor: jhoto
      target: lib/main_jhoto.dart
    secrets:
      SIGNING_KEYSTORE: ${{ secrets.JHOTO_KEYSTORE }}
      SIGNING_KEY_ALIAS: ${{ secrets.JHOTO_SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

  build_ios_kanto:
    uses: ./.github/workflows/_build_ios.yml
    needs: flutter_test
    with:
      flavor: kanto
      target: lib/main_kanto.dart

  build_ios_jhoto:
    uses: ./.github/workflows/_build_ios.yml
    needs: flutter_test
    with:
      flavor: jhoto
      target: lib/main_jhoto.dart