name: upload-all-pokedex

on:
  push:
    branches:
      - master

jobs:
  upload-kanto_pokedex:
    uses: ./.github/workflows/_upload_pokedex.yml
    with:
      flavor: "kanto"
  upload-jhoto_pokedex:
    uses: ./.github/workflows/_upload_pokedex.yml
    with:
      flavor: "jhoto"
